# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "vagrant-centos6-amd64"
  config.vm.box_url = "https://www.dropbox.com/s/4hr24xut3kb1uxz/vagrant-centos6-amd64.box?dl=1"
  config.vm.provision :shell, path: "https://raw.githubusercontent.com/charleslieferando/vagrant/master/nodes/nginx/centos/bootstrap.sh"
  config.vm.provision :shell, path: "bootstrap.sh"
  
  config.vm.hostname = "bafin-nginx"
  config.vm.network "private_network", ip: "192.168.0.44"
  config.vm.network "forwarded_port", guest: 80, host: 7071

  config.vm.provider "virtualbox" do |v|
    v.name = "bafin-nginx"
    v.customize ["modifyvm", :id, "--memory", "512"]
  end
  
end
