# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "vagrant-ubuntu14-amd64"
  config.vm.box_url = "https://www.dropbox.com/s/5sfrsa3omzyknc8/vagrant-ubuntu14-amd64.box?dl=1"

end
