# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "vagrant-centos6-amd64"
  config.vm.box_url = "https://www.dropbox.com/s/4hr24xut3kb1uxz/vagrant-centos6-amd64.box?dl=1"

end
